import 'package:mindpilot/export.dart';
import '../models/agent_action.dart';

/// Interactive UI Card rendering a checkable, multi-step action plan generated by the AI agent.
class ActionPlanCard extends StatefulWidget {
  final AgentAction action;
  final VoidCallback? onStatusChanged;

  const ActionPlanCard({
    super.key,
    required this.action,
    this.onStatusChanged,
  });

  @override
  State<ActionPlanCard> createState() => _ActionPlanCardState();
}

class _ActionPlanCardState extends State<ActionPlanCard> {
  List<Map<String, dynamic>> _getTasks() {
    final raw = widget.action.arguments['tasks'];
    if (raw is List) {
      return raw.whereType<Map>().map((m) => Map<String, dynamic>.from(m)).toList();
    }
    return [];
  }

  void _toggleTask(int index) {
    final tasks = _getTasks();
    if (index >= 0 && index < tasks.length) {
      final current = tasks[index]['is_completed'] as bool? ?? false;
      tasks[index]['is_completed'] = !current;
      widget.action.arguments['tasks'] = tasks;
      setState(() {});
      widget.onStatusChanged?.call();
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = context.watch<AppTheme>();
    final title = (widget.action.arguments['plan_title'] as String?) ?? widget.action.title;
    final tasks = _getTasks();
    final completedCount = tasks.where((t) => (t['is_completed'] as bool? ?? false)).length;
    final totalCount = tasks.length;
    final progress = totalCount > 0 ? (completedCount / totalCount) : 0.0;
    final allCompleted = totalCount > 0 && completedCount == totalCount;

    return Container(
      margin: EdgeInsets.only(top: 8.h, bottom: 4.h),
      padding: EdgeInsets.all(14.w),
      decoration: BoxDecoration(
        color: theme.primaryBase.withValues(alpha: 0.07),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: allCompleted
              ? Colors.greenAccent.withValues(alpha: 0.6)
              : theme.primaryBase.withValues(alpha: 0.35),
          width: 1.2,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header Row
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(6),
                decoration: BoxDecoration(
                  color: allCompleted
                      ? Colors.greenAccent.withValues(alpha: 0.2)
                      : theme.primaryBase.withValues(alpha: 0.2),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Icon(
                  allCompleted ? Icons.check_circle_outline : Icons.checklist_rtl_rounded,
                  size: 18,
                  color: allCompleted ? Colors.greenAccent : theme.primaryBase,
                ),
              ),
              10.horizontalSpace,
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      title,
                      style: TextStyle(
                        fontSize: 14,
                        fontWeight: FontWeight.bold,
                        color: theme.accentTxt,
                      ),
                    ),
                    2.verticalSpace,
                    Text(
                      allCompleted
                          ? 'All $totalCount steps finished! 🎉'
                          : '$completedCount of $totalCount completed (${(progress * 100).toInt()}%)',
                      style: TextStyle(
                        fontSize: 11,
                        color: allCompleted ? Colors.greenAccent : theme.accentTxt.withValues(alpha: 0.6),
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),

          10.verticalSpace,

          // Progress Bar
          ClipRRect(
            borderRadius: BorderRadius.circular(4),
            child: LinearProgressIndicator(
              value: progress,
              minHeight: 5,
              backgroundColor: theme.accentTxt.withValues(alpha: 0.1),
              valueColor: AlwaysStoppedAnimation<Color>(
                allCompleted ? Colors.greenAccent : theme.primaryBase,
              ),
            ),
          ),

          12.verticalSpace,

          // Tasks List
          ...tasks.asMap().entries.map((entry) {
            final idx = entry.key;
            final task = entry.value;
            final isDone = task['is_completed'] as bool? ?? false;
            final taskTitle = task['title'] as String? ?? 'Step ${idx + 1}';
            final estMinutes = task['estimated_minutes'] as num?;

            return InkWell(
              onTap: () => _toggleTask(idx),
              borderRadius: BorderRadius.circular(8),
              child: Padding(
                padding: EdgeInsets.symmetric(vertical: 4.h, horizontal: 2.w),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Icon(
                      isDone ? Icons.check_box : Icons.check_box_outline_blank,
                      size: 20,
                      color: isDone ? Colors.greenAccent : theme.accentTxt.withValues(alpha: 0.4),
                    ),
                    10.horizontalSpace,
                    Expanded(
                      child: Text(
                        taskTitle,
                        style: TextStyle(
                          fontSize: 13,
                          color: isDone
                              ? theme.accentTxt.withValues(alpha: 0.4)
                              : theme.accentTxt,
                          decoration: isDone ? TextDecoration.lineThrough : null,
                          fontWeight: isDone ? FontWeight.normal : FontWeight.w500,
                        ),
                      ),
                    ),
                    if (estMinutes != null && estMinutes > 0)
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                        decoration: BoxDecoration(
                          color: theme.accentTxt.withValues(alpha: 0.08),
                          borderRadius: BorderRadius.circular(6),
                        ),
                        child: Text(
                          '${estMinutes}m',
                          style: TextStyle(
                            fontSize: 10,
                            color: theme.accentTxt.withValues(alpha: 0.5),
                          ),
                        ),
                      ),
                  ],
                ),
              ),
            );
          }),
        ],
      ),
    );
  }
}
