// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4J2z380yMB7ToJDTyoZZhLjPoyiqw-3s',
    appId: '1:802202587833:web:6af45f6d6223702d580168',
    messagingSenderId: '802202587833',
    projectId: 'mindpilot-131f1',
    authDomain: 'mindpilot-131f1.firebaseapp.com',
    storageBucket: 'mindpilot-131f1.firebasestorage.app',
    measurementId: 'G-VCJHSPJF1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD84oPtOAZ2DZz2F4wgS96-BAUneA1n-Zk',
    appId: '1:802202587833:android:6d03cf3b6f38a877580168',
    messagingSenderId: '802202587833',
    projectId: 'mindpilot-131f1',
    storageBucket: 'mindpilot-131f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGHTisrJ5CJXYedrChuJIAyevi1yPfsXM',
    appId: '1:802202587833:ios:9e48c83870ff102f580168',
    messagingSenderId: '802202587833',
    projectId: 'mindpilot-131f1',
    storageBucket: 'mindpilot-131f1.firebasestorage.app',
    iosClientId: '802202587833-6u4ljq0ulaqpu4gr8rf77ltopvp6ujem.apps.googleusercontent.com',
    iosBundleId: 'com.example.archonitDevTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGHTisrJ5CJXYedrChuJIAyevi1yPfsXM',
    appId: '1:802202587833:ios:9e48c83870ff102f580168',
    messagingSenderId: '802202587833',
    projectId: 'mindpilot-131f1',
    storageBucket: 'mindpilot-131f1.firebasestorage.app',
    iosClientId: '802202587833-6u4ljq0ulaqpu4gr8rf77ltopvp6ujem.apps.googleusercontent.com',
    iosBundleId: 'com.example.archonitDevTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4J2z380yMB7ToJDTyoZZhLjPoyiqw-3s',
    appId: '1:802202587833:web:9a845f3c432e4848580168',
    messagingSenderId: '802202587833',
    projectId: 'mindpilot-131f1',
    authDomain: 'mindpilot-131f1.firebaseapp.com',
    storageBucket: 'mindpilot-131f1.firebasestorage.app',
    measurementId: 'G-73R9ZYQ3GV',
  );
}
