enum ActionStatus {
  pendingApproval,
  executing,
  completed,
  failed,
  dismissed,
}

/// Represents a discrete action or tool invocation generated by the AI agent.
class AgentAction {
  final String id;
  final String toolName;
  final String title;
  final String description;
  final Map<String, dynamic> arguments;
  ActionStatus status;
  dynamic result;
  String? errorMessage;
  final DateTime createdAt;

  AgentAction({
    required this.id,
    required this.toolName,
    required this.title,
    required this.description,
    required this.arguments,
    this.status = ActionStatus.pendingApproval,
    this.result,
    this.errorMessage,
    DateTime? createdAt,
  }) : createdAt = createdAt ?? DateTime.now();

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'toolName': toolName,
      'title': title,
      'description': description,
      'arguments': arguments,
      'status': status.name,
      'result': result,
      'errorMessage': errorMessage,
      'createdAt': createdAt.toIso8601String(),
    };
  }

  factory AgentAction.fromJson(Map<String, dynamic> json) {
    return AgentAction(
      id: json['id'] as String,
      toolName: json['toolName'] as String,
      title: json['title'] as String,
      description: json['description'] as String,
      arguments: Map<String, dynamic>.from(json['arguments'] as Map? ?? {}),
      status: ActionStatus.values.firstWhere(
        (e) => e.name == json['status'],
        orElse: () => ActionStatus.pendingApproval,
      ),
      result: json['result'],
      errorMessage: json['errorMessage'] as String?,
      createdAt: json['createdAt'] != null
          ? DateTime.tryParse(json['createdAt'] as String) ?? DateTime.now()
          : DateTime.now(),
    );
  }
}
